# Generated by Django 3.0.7 on 2021-02-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('bookImage', models.ImageField(blank=True, default='images/book/defaultBook.jpg', null=True, upload_to='images/book')),
                ('bookName', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('inProcess', 'inProcess'), ('sold', 'sold')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('calculatorId', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('used', 'used'), ('new', 'new')], default='used', max_length=4)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('inStock', 'inStock'), ('inProcess', 'inProcess'), ('sold', 'sold')], default='inStock', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coat',
            fields=[
                ('coatId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('inStock', 'inStock'), ('inProcess', 'inProcess'), ('sold', 'sold')], default='inStock', max_length=10)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=10)),
                ('condition', models.CharField(choices=[('used', 'used'), ('new', 'new')], default='used', max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
                ('year', models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('LY', 'LY')], default='FY', max_length=2)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('COMPS', 'COMPS'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('MECH', 'MECH')], default='IT', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullName', models.CharField(max_length=255)),
                ('password', models.CharField(editable=False, max_length=20)),
                ('confirmPassword', models.CharField(editable=False, max_length=20)),
                ('contactNumber', models.CharField(max_length=12)),
                ('year', models.CharField(choices=[('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY'), ('LY', 'LY')], default='FY', max_length=2)),
                ('branch', models.CharField(choices=[('IT', 'IT'), ('COMPS', 'COMPS'), ('EXTC', 'EXTC'), ('ETRX', 'ETRX'), ('MECH', 'MECH')], default='IT', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('suitId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('inStock', 'inStock'), ('inProcess', 'inProcess'), ('sold', 'sold')], default='inStock', max_length=10)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('condition', models.CharField(choices=[('used', 'used'), ('new', 'new')], default='used', max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suits', to='ccapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_books', to='ccapp.Book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_books', to='ccapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Toolkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_toolkits', to='ccapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Suit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flag_seller_complete', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('flag_customer_complete', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_suits', to='ccapp.Student')),
                ('suit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_suits', to='ccapp.Suit')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Coat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flag_seller_complete', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('flag_customer_complete', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('coat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_coats', to='ccapp.Coat')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_coats', to='ccapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flag_seller_complete', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('flag_customer_complete', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('calculator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_calculators', to='ccapp.Calculator')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_calculators', to='ccapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flag_seller_complete', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('flag_customer_complete', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='ccapp.Book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_books', to='ccapp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='coat',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coats', to='ccapp.Student'),
        ),
        migrations.AddField(
            model_name='calculator',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculators', to='ccapp.Student'),
        ),
        migrations.AddField(
            model_name='book',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='ccapp.Student'),
        ),
    ]
