# Generated by Django 3.0.7 on 2021-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='confirmPassword',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(editable=False, max_length=500),
        ),
    ]
