# Generated by Django 3.0.7 on 2021-02-14 13:52

import ccapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0002_auto_20210207_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookImage',
            field=models.ImageField(blank=True, default='images/book/defaultBook.jpg', null=True, upload_to=ccapp.models.upload_location),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('inProcess', 'inProcess'), ('sold', 'sold'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
